import React from "react";
import styles from "../styles/ThankYou.module.css";
import Head from "next/head";
import Image from "next/image";
import { AiOutlineDownload } from "react-icons/ai";
import { BsArrowLeftShort } from "react-icons/bs";
import Link from "next/link";

const ThankYou = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Thank you</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className={styles.mains}>
        <div className={styles.left}>
          <h4 className={styles.hptop}>
            <b>Thank you</b>
            <br />
            for showing interest in the program
          </h4>
          <p className={styles.Ptop}>
            We have shared the program brochure with you over an email. Have a
            great day !
          </p>
          <div>
            <div className={styles.mainb}>
              <div>
                <button className={styles.Button}>
                  <BsArrowLeftShort className="bIcons" />
                  <Link href="/Data-Science-course">Back To Course</Link>
                </button>
              </div>
              <div>
                <button className={styles.Button}>
                  <AiOutlineDownload className="bIcons" />
                  <Link href="https://drive.google.com/file/d/171OMPROIplCmW8Oz6t5ihsa3rr0U7Gm-/view?usp=sharing">
                    Download Brochure
                  </Link>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.right}>
          <Image
            src="/thank-you.png"
            alt="data-science-course"
            quality={100}
            layout="intrinsic"
            width="500"
            height="550"
          />
        </div>
      </section>
    </div>
  );
};

export default ThankYou;
